[package]
name = "explorer"
version = "1.7.9"
description = "A native macOS filesystem explorer"
authors = ["Jerome Purushotham"]
edition = "2021"

[lib]
name = "explorer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api", "protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-os = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
directories = "5"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
urlencoding = "2"
http = "1"
kamadak-exif = "0.5"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "gif"] }
sha2 = "0.10"
trash = "5"
rusqlite = { version = "0.31", features = ["bundled", "bundled-full"] }
notify = "6"
strsim = "0.11"
git2 = { version = "0.19", features = ["vendored-openssl"] }
keyring = "3"
uuid = { version = "1", features = ["v4", "serde"] }
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2"
zip = { version = "2", default-features = false, features = ["deflate"] }
flate2 = "1"
tar = "0.4"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-foundation = "0.3"
raw-window-handle = "0.6"
